# Generated by Django 3.2.7 on 2021-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0005_auto_20210913_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique_for_date='publish'),
        ),
    ]
